# Generated by Django 3.0.7 on 2020-06-03 23:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materiais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=300)),
                ('datacompra', models.DateField()),
                ('datavalidade', models.DateField()),
                ('quantidade', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('custo', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
            ],
        ),
    ]
